<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Aarti Rathi',
                'email' => 'hrconnect@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aarti',
                'last_name' => 'Rathi',
                'phone' => '+919910281749',
                'team_id' => '2',
                'salary' => 21600,
                'date_of_joining' => '2024-02-05',
            ],
            [
                'name' => 'Aishwarya',
                'email' => 'Aishwarya@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aishwarya',
                'last_name' => '',
                'phone' => '+919999999902',
                'team_id' => '3',
                'salary' => 15000,
                'date_of_joining' => '2025-08-20',
            ],
            [
                'name' => 'Aman Gupta',
                'email' => 'aman.gupta@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aman',
                'last_name' => 'Gupta',
                'phone' => '+919999999903',
                'team_id' => '3',
                'salary' => 42000,
                'date_of_joining' => '2022-07-20',
            ],
            [
                'name' => 'Anurag Sharma',
                'email' => 'anurag@digirockett.com',
                'password' => 'password',
                'first_name' => 'Anurag',
                'last_name' => 'Sharma',
                'phone' => '+919354517293',
                'team_id' => '7',
                'salary' => 59800,
                'date_of_joining' => '2023-10-17',
            ],
            [
                'name' => 'Apoorv Dwivedi',
                'email' => 'apoorv@digirockett.com',
                'password' => 'password',
                'first_name' => 'Apoorv',
                'last_name' => 'Dwivedi',
                'phone' => '+919711574747',
                'team_id' => '1',
                'salary' => 60000,
                'date_of_joining' => '2023-07-19',
            ],

            [
                'name' => 'Bhumika Singh',
                'email' => 'Bhumika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Bhumika',
                'last_name' => 'Singh',
                'phone' => '+919999999906',
                'team_id' => '8',
                'salary' => 30000,
                'date_of_joining' => '2025-07-21',
            ],

            [
                'name' => 'Garvit Sharma',
                'email' => 'garvit.sharma@digirockett.com',
                'password' => 'password',
                'first_name' => 'Garvit',
                'last_name' => 'Sharma',
                'phone' => '+917976079825',
                'team_id' => '5',
                'salary' => 35000,
                'date_of_joining' => '2024-12-02',
            ],

            [
                'name' => 'Gracie Lamnunnem Chongloi',
                'email' => 'gracie@digirockett.com',
                'password' => 'password',
                'first_name' => 'Gracie',
                'last_name' => 'Lamnunnem Chongloi',
                'phone' => '+919999999908',
                'team_id' => '3',
                'salary' => 38000,
                'date_of_joining' => '2025-10-21',
            ],

            [
                'name' => 'Harsh Bhargav',
                'email' => 'harsh.b@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harsh',
                'last_name' => 'Bhargav',
                'phone' => '+919999999909',
                'team_id' => '3',
                'salary' => 32500,
                'date_of_joining' => '2024-09-16',
            ],
            [
                'name' => 'Harsh Raj',
                'email' => 'Harsh.raj@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harsh',
                'last_name' => 'Raj',
                'phone' => '+919999999910',
                'team_id' => '3',
                'salary' => 39000,
                'date_of_joining' => '2024-07-17',
            ],
            [
                'name' => 'Harshdeep Singh',
                'email' => 'Harshdeep@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harshdeep',
                'last_name' => 'Singh',
                'phone' => '+919999999911',
                'team_id' => '6',
                'salary' => 15000,
                'date_of_joining' => '2025-10-06',
            ],
            [
                'name' => 'Harshit Singla',
                'email' => 'harshit.singla@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harshit',
                'last_name' => 'Singla',
                'phone' => '+919991665833',
                'team_id' => '7',
                'salary' => 10000,
                'date_of_joining' => '2025-08-08',
            ],
            [
                'name' => 'Kajal Singh',
                'email' => 'kajal.s@digirockett.com',
                'password' => 'password',
                'first_name' => 'Kajal',
                'last_name' => 'Singh',
                'phone' => '+919999999914',
                'team_id' => '5',
                'salary' => 10000,
                'date_of_joining' => '2025-07-04',
            ],
            [
                'name' => 'Kanika Jain',
                'email' => 'Kanika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Kanika',
                'last_name' => 'Jain',
                'phone' => '+919999999915',
                'team_id' => '6',
                'salary' => 15000,
                'date_of_joining' => '2025-08-25',
            ],
            [
                'name' => 'Keshav Pundir',
                'email' => 'Keshav@digirockett.com',
                'password' => 'password',
                'first_name' => 'Keshav',
                'last_name' => 'Pundir',
                'phone' => '+919999999916',
                'team_id' => '3',
                'salary' => 30000,
                'date_of_joining' => '2025-08-08',
            ],
            [
                'name' => 'Ketou Nakhro',
                'email' => 'Ketou@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ketou',
                'last_name' => 'Nakhro',
                'phone' => '+919999999917',
                'team_id' => '3',
                'salary' => 30000,
                'date_of_joining' => '2025-10-10',
            ],
            [
                'name' => 'Lalit Nailwal',
                'email' => 'Lalit@digirockett.com',
                'password' => 'password',
                'first_name' => 'Lalit',
                'last_name' => 'Nailwal',
                'phone' => '+919999999918',
                'team_id' => '3',
                'salary' => 100000,
                'date_of_joining' => '2025-09-25',
            ],
            [
                'name' => 'Mahfooz Alam',
                'email' => 'Mahfooz.alam@digirockett.com',
                'password' => 'password',
                'first_name' => 'Mahfooz',
                'last_name' => 'Alam',
                'phone' => '+919650237385',
                'team_id' => '4',
                'salary' => 15000,
                'date_of_joining' => '202-02-12',
            ],
            [
                'name' => 'Navneet Raj',
                'email' => 'raj.navneet@digirockett.com',
                'password' => 'password',
                'first_name' => 'Navneet',
                'last_name' => 'Raj',
                'phone' => '+919999999920',
                'team_id' => '5',
                'salary' => 24000,
                'date_of_joining' => '2024-08-08',
            ],
            [
                'name' => 'Nikhar Makkar',
                'email' => 'nikhar.makkar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Nikhar',
                'last_name' => 'Makkar',
                'phone' => '+918837614969',
                'team_id' => '10',
                'salary' => 44000,
                'date_of_joining' => '2022-05-02',
            ],
            [
                'name' => 'Nitesh Srivastava',
                'email' => 'nitesh.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Nitesh',
                'last_name' => 'Srivastava',
                'phone' => '+919451743582',
                'team_id' => '5',
                'salary' => 26000,
                'date_of_joining' => '2022-07-25',
            ],
            [
                'name' => 'Pratyaksh Srivastava ',
                'email' => 'pratyaksh.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Pratyaksh',
                'last_name' => 'Srivastava',
                'phone' => '+919999999924',
                'team_id' => '6',
                'salary' => 27500,
                'date_of_joining' => '2024-12-15',
            ],
            [
                'name' => 'Radhika Sharma',
                'email' => 'radhika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Radhika',
                'last_name' => 'Sharma',
                'phone' => '+919999999926',
                'team_id' => '10',
                'salary' => 25000,
                'date_of_joining' => '2025-10-22',
            ],
            [
                'name' => 'Ritesh Saxena',
                'email' => 'Ritesh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ritesh',
                'last_name' => 'Saxena',
                'phone' => '+919999999928',
                'team_id' => '3',
                'salary' => 42000,
                'date_of_joining' => '2025-07-21',
            ],
            [
                'name' => 'Ritika Singh',
                'email' => 'ritika.singh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ritika',
                'last_name' => 'Singh',
                'phone' => '+919905484507',
                'team_id' => '4',
                'salary' => 30000,
                'date_of_joining' => '2025-05-19',
            ],
            [
                'name' => 'Sakshi Kushwaha',
                'email' => 'sakshi.Kushwaha@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sakshi',
                'last_name' => 'Kushwaha',
                'phone' => '+919999999931',
                'team_id' => '6',
                'salary' => 20000,
                'date_of_joining' => '2025-05-01',
            ],
            [
                'name' => 'Sanjeev Kumar',
                'email' => 'sanjeev@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sanjeev',
                'last_name' => 'Kumar',
                'phone' => '+917004202248',
                'team_id' => '5',
                'salary' => 32000,
                'date_of_joining' => '2022-08-01',
            ],
            [
                'name' => 'Shashwat Srivastava',
                'email' => 'shashwat.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shashwat',
                'last_name' => 'Srivastava',
                'phone' => '+918948628976',
                'team_id' => '7',
                'salary' => 30000,
                'date_of_joining' => '2024-07-15',
            ],
            [
                'name' => 'Shreya Karkera',
                'email' => 'Shreya@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shreya',
                'last_name' => 'Karkera',
                'phone' => '+919999999936',
                'team_id' => '3',
                'salary' => 39000,
                'date_of_joining' => '2023-07-03',
            ],
            [
                'name' => 'Shubhranshu Srivastava',
                'email' => 'shubh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shubhranshu',
                'last_name' => 'Srivastava',
                'phone' => '+918860301476',
                'team_id' => '1',
                'salary' => 200000,
                'date_of_joining' => '2022-04-01',
            ],
            [
                'name' => 'Shweta Singh',
                'email' => 'shweta.singh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shweta',
                'last_name' => 'Singh',
                'phone' => '+919999999938',
                'team_id' => '10',
                'salary' => 25000,
                'date_of_joining' => '2025-05-09',
            ],
            [
                'name' => 'Sidharth Anant',
                'email' => 'sidharth.anant@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sidharth',
                'last_name' => 'Anant',
                'phone' => '+917830010567',
                'team_id' => '10',
                'salary' => 80000,
                'date_of_joining' => '2022-07-04',
            ],
            [
                'name' => 'Sohan Kumar',
                'email' => 'sohan.kumar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sohan',
                'last_name' => 'Kumar',
                'phone' => '+919113782646',
                'team_id' => '5',
                'salary' => 26000,
                'date_of_joining' => '2023-07-25',
            ],
            [
                'name' => 'Sumit Sisodiya',
                'email' => 'sumit.s@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sumit',
                'last_name' => 'Sisodiya',
                'phone' => '+919999999942',
                'team_id' => '5',
                'salary' => 15000,
                'date_of_joining' => '2025-06-23',
            ],
            [
                'name' => 'Sunny Kumar',
                'email' => 'sunny@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sunny',
                'last_name' => 'Kumar',
                'phone' => '+918505902240',
                'team_id' => '1',
                'salary' => 200000,
                'date_of_joining' => '2022-04-01',
            ],
            [
                'name' => 'Suraj Kumar',
                'email' => 'suraj.kumar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Suraj',
                'last_name' => 'Kumar',
                'phone' => '+918340207969',
                'team_id' => '3',
                'salary' => 39000,
                'date_of_joining' => '2023-07-17',
            ],
            [
                'name' => 'Suresh Vishnoi',
                'email' => 'suresh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Suresh',
                'last_name' => 'Vishnoi',
                'phone' => '+919999999945',
                'team_id' => '3',
                'salary' => 30000,
                'date_of_joining' => '2025-09-16',
            ],
            [
                'name' => 'Swadha Mishra',
                'email' => 'Swadha.Mishra@digirockett.com',
                'password' => 'password',
                'first_name' => 'Swadha',
                'last_name' => 'Mishra',
                'phone' => '+919999999946',
                'team_id' => '5',
                'salary' => 25000,
                'date_of_joining' => '2025-01-06',
            ],
            [
                'name' => 'Ujjawal Srivastava',
                'email' => 'Ujjawal@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ujjawal',
                'last_name' => 'Srivastava',
                'phone' => '+919999999947',
                'team_id' => '5',
                'salary' => 10000,
                'date_of_joining' => '2025-07-05',
            ],
            [
                'name' => 'Upasana Rathore',
                'email' => 'upasana.rathore@digirockett.com',
                'password' => 'password',
                'first_name' => 'Upasana',
                'last_name' => 'Rathore',
                'phone' => '+917033249191',
                'team_id' => '4',
                'salary' => 40700,
                'date_of_joining' => '2023-06-12',
            ],
            [
                'name' => 'Aman Mahto',
                'email' => 'aman.m@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aman',
                'last_name' => 'Mahto',
                'phone' => '+919999999948',
                'team_id' => '4',
                'salary' => 25000,
                'date_of_joining' => '2023-11-13',
            ],
            // [
            // [
            //     'name' => 'Harshvardhan Singh',
            //     'email' => 'Harshvardhan@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Harshvardhan',
            //     'last_name' => 'Singh',
            //     'phone' => '+919999999913',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Sudhanshu Awasthi',
            //     'email' => 'sudhanshu.awasthi@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Sudhanshu',
            //     'last_name' => 'Awasthi',
            //     'phone' => '+919999999941',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Shivam Dave',
            //     'email' => 'Shivam@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Shivam',
            //     'last_name' => 'Dave',
            //     'phone' => '+919999999935',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Samiksha Kaushik',
            //     'email' => 'samiksha@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Samiksha',
            //     'last_name' => 'Kaushik',
            //     'phone' => '+919999999932',
            //     'team_id' => '3',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Sakeena',
            //     'email' => 'sakeena@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Sakeena',
            //     'last_name' => '',
            //     'phone' => '+919999999930',
            //     'team_id' => '3',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Ravikant',
            //     'email' => 'Ravikant@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Ravikant',
            //     'last_name' => '',
            //     'phone' => '+919999999927',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Nikhil Srivastava',
            //     'email' => 'Nikhil.srivastava@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Nikhil',
            //     'last_name' => 'Srivastava',
            //     'phone' => '+919999999922',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],

        ];

        foreach ($users as $userData) {
            // Create the user
            $user = User::create([
                'name' => $userData['name'],
                'email' => $userData['email'],
                'password' => Hash::make($userData['password']),
                'email_verified_at' => now(),
                'is_active' => 1,
            ]);

            // Create the corresponding employee record
            // Note: reporting_manager_id will be set by ReportingManagerSeeder
            Employee::create([
                'user_id' => $user->id,
                'first_name' => $userData['first_name'],
                'last_name' => $userData['last_name'],
                'phone' => $userData['phone'],
                'team_id' => $userData['team_id'],
                'salary' => $userData['salary'],
                'date_of_joining' => $userData['date_of_joining'],
            ]);
        }
    }
}
