<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Aarti Rathi',
                'email' => 'hrconnect@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aarti',
                'last_name' => 'Rathi',
                'phone' => '+919999999901',
                'team_id' => '2',
            ],
            [
                'name' => 'Aishwarya',
                'email' => 'Aishwarya@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aishwarya',
                'last_name' => '',
                'phone' => '+919999999902',
                'team_id' => '3',
            ],
            [
                'name' => 'Aman Gupta',
                'email' => 'aman.gupta@digirockett.com',
                'password' => 'password',
                'first_name' => 'Aman',
                'last_name' => 'Gupta',
                'phone' => '+919999999903',
                'team_id' => '3',
            ],
            [
                'name' => 'Anurag Sharma',
                'email' => 'anurag@digirockett.com',
                'password' => 'password',
                'first_name' => 'Anurag',
                'last_name' => 'Sharma',
                'phone' => '+919999999904',
                'team_id' => '7',
            ],
            [
                'name' => 'Apoorv Dwivedi',
                'email' => 'apoorv@digirockett.com',
                'password' => 'password',
                'first_name' => 'Apoorv',
                'last_name' => 'Dwivedi',
                'phone' => '+919999999905',
                'team_id' => '1',
            ],
 
            [
                'name' => 'Bhumika Singh',
                'email' => 'Bhumika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Bhumika',
                'last_name' => 'Singh',
                'phone' => '+919999999906',
                'team_id' => '8',
            ],
 
            [
                'name' => 'Garvit Sharma',
                'email' => 'garvit.sharma@digirockett.com',
                'password' => 'password',
                'first_name' => 'Garvit',
                'last_name' => 'Sharma',
                'phone' => '+919999999907',
                'team_id' => '5',
            ],
 
            [
                'name' => 'Gracie Lamnunnem Chongloi',
                'email' => 'gracie@digirockett.com',
                'password' => 'password',
                'first_name' => 'Gracie',
                'last_name' => 'Lamnunnem Chongloi',
                'phone' => '+919999999908',
                'team_id' => '3',
            ],
 
            [
                'name' => 'Harsh Bhargav',
                'email' => 'harsh.b@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harsh',
                'last_name' => 'Bhargav',
                'phone' => '+919999999909',
                'team_id' => '3',
            ], 
            [
                'name' => 'Harsh Raj',
                'email' => 'Harsh.raj@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harsh',
                'last_name' => 'Raj',
                'phone' => '+919999999910',
                'team_id' => '3',
            ],
            [
                'name' => 'Harshdeep Singh',
                'email' => 'Harshdeep@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harshdeep',
                'last_name' => 'Singh',
                'phone' => '+919999999911',
                'team_id' => '6',
            ],
            [
                'name' => 'Harshit Singla',
                'email' => 'harshit.singla@digirockett.com',
                'password' => 'password',
                'first_name' => 'Harshit',
                'last_name' => 'Singla',
                'phone' => '+919999999912',
                'team_id' => '7',
            ],
            [
                'name' => 'Kajal Singh',
                'email' => 'kajal.s@digirockett.com',
                'password' => 'password',
                'first_name' => 'Kajal',
                'last_name' => 'Singh',
                'phone' => '+919999999914',
                'team_id' => '5',
            ],
            [
                'name' => 'Kanika Jain',
                'email' => 'Kanika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Kanika',
                'last_name' => 'Jain',
                'phone' => '+919999999915',
                'team_id' => '6',
            ],
            [
                'name' => 'Keshav Pundir',
                'email' => 'Keshav@digirockett.com',
                'password' => 'password',
                'first_name' => 'Keshav',
                'last_name' => 'Pundir',
                'phone' => '+919999999916',
                'team_id' => '3',
            ],
            [
                'name' => 'Ketou Nakhro',
                'email' => 'Ketou@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ketou',
                'last_name' => 'Nakhro',
                'phone' => '+919999999917',
                'team_id' => '3',
            ],
            [
                'name' => 'Lalit Nailwal',
                'email' => 'Lalit@digirockett.com',
                'password' => 'password',
                'first_name' => 'Lalit',
                'last_name' => 'Nailwal',
                'phone' => '+919999999918',
                'team_id' => '3',
            ],
            [
                'name' => 'Mahfooz Alam',
                'email' => 'Mahfooz.alam@digirockett.com',
                'password' => 'password',
                'first_name' => 'Mahfooz',
                'last_name' => 'Alam',
                'phone' => '+919999999919',
                'team_id' => '4',
            ],
            [
                'name' => 'Navneet Raj',
                'email' => 'raj.navneet@digirockett.com',
                'password' => 'password',
                'first_name' => 'Navneet',
                'last_name' => 'Raj',
                'phone' => '+919999999920',
                'team_id' => '5',
            ],
            [
                'name' => 'Nikhar Makkar',
                'email' => 'nikhar.makkar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Nikhar',
                'last_name' => 'Makkar',
                'phone' => '+919999999921',
                'team_id' => '10',
            ],
            [
                'name' => 'Nitesh Srivastava',
                'email' => 'nitesh.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Nitesh',
                'last_name' => 'Srivastava',
                'phone' => '+919999999923',
                'team_id' => '5',
            ],
            [
                'name' => 'Pratyaksh Srivastava ',
                'email' => 'pratyaksh.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Pratyaksh',
                'last_name' => 'Srivastava',
                'phone' => '+919999999924',
                'team_id' => '6',
            ],
            [
                'name' => 'Radhika Sharma',
                'email' => 'radhika@digirockett.com',
                'password' => 'password',
                'first_name' => 'Radhika',
                'last_name' => 'Sharma',
                'phone' => '+919999999926',
                'team_id' => '10',
            ],
            [
                'name' => 'Ritesh Saxena',
                'email' => 'Ritesh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ritesh',
                'last_name' => 'Saxena',
                'phone' => '+919999999928',
                'team_id' => '3',
            ],
            [
                'name' => 'Ritika Singh',
                'email' => 'ritika.singh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ritika',
                'last_name' => 'Singh',
                'phone' => '+919999999929',
                'team_id' => '4',
            ],
            [
                'name' => 'Sakshi Kushwaha',
                'email' => 'sakshi.Kushwaha@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sakshi',
                'last_name' => 'Kushwaha',
                'phone' => '+919999999931',
                'team_id' => '6',
            ],
            [
                'name' => 'Sanjeev Kumar',
                'email' => 'sanjeev@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sanjeev',
                'last_name' => 'Kumar',
                'phone' => '+919999999933',
                'team_id' => '5',
            ],
            [
                'name' => 'Shashwat Srivastava',
                'email' => 'shashwat.srivastava@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shashwat',
                'last_name' => 'Srivastava',
                'phone' => '+919999999934',
                'team_id' => '7',
            ],      
            [
                'name' => 'Shreya Karkera',
                'email' => 'Shreya@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shreya',
                'last_name' => 'Karkera',
                'phone' => '+919999999936',
                'team_id' => '3',
            ],
            [
                'name' => 'Shubhranshu Srivastava',
                'email' => 'shubh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shubhranshu',
                'last_name' => 'Srivastava',
                'phone' => '+919999999937',
                'team_id' => '1',
            ],
            [
                'name' => 'Shweta Singh',
                'email' => 'shweta.singh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Shweta',
                'last_name' => 'Singh',
                'phone' => '+919999999938',
                'team_id' => '10',
            ],
            [
                'name' => 'Sidharth Anant',
                'email' => 'sidharth.anant@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sidharth',
                'last_name' => 'Anant',
                'phone' => '+919999999939',
                'team_id' => '10',
            ],
            [
                'name' => 'Sohan Kumar',
                'email' => 'sohan.kumar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sohan',
                'last_name' => 'Kumar',
                'phone' => '+919999999940',
                'team_id' => '5',
            ],
            [
                'name' => 'Sumit Sisodiya',
                'email' => 'sumit.s@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sumit',
                'last_name' => 'Sisodiya',
                'phone' => '+919999999942',
                'team_id' => '5',
            ],
            [
                'name' => 'Sunny Kumar',
                'email' => 'sunny@digirockett.com',
                'password' => 'password',
                'first_name' => 'Sunny',
                'last_name' => 'Kumar',
                'phone' => '+919999999943',
                'team_id' => '1',
            ],
            [
                'name' => 'Suraj Kumar',
                'email' => 'suraj.kumar@digirockett.com',
                'password' => 'password',
                'first_name' => 'Suraj',
                'last_name' => 'Kumar',
                'phone' => '+919999999944',
                'team_id' => '3',
            ],
            [
                'name' => 'Suresh Vishnoi',
                'email' => 'suresh@digirockett.com',
                'password' => 'password',
                'first_name' => 'Suresh',
                'last_name' => 'Vishnoi',
                'phone' => '+919999999945',
                'team_id' => '3',
            ],
            [
                'name' => 'Swadha Mishra',
                'email' => 'Swadha.Mishra@digirockett.com',
                'password' => 'password',
                'first_name' => 'Swadha',
                'last_name' => 'Mishra',
                'phone' => '+919999999946',
                'team_id' => '5',
            ],
            [
                'name' => 'Ujjawal Srivastava',
                'email' => 'Ujjawal@digirockett.com',
                'password' => 'password',
                'first_name' => 'Ujjawal',
                'last_name' => 'Srivastava',
                'phone' => '+919999999947',
                'team_id' => '5',
            ],
            [
                'name' => 'Upasana Rathore',
                'email' => 'upasana.rathore@digirockett.com',
                'password' => 'password',
                'first_name' => 'Upasana',
                'last_name' => 'Rathore',
                'phone' => '+919999999948',
                'team_id' => '4',
            ],
            // [
            //     'name' => 'Harshvardhan Singh',
            //     'email' => 'Harshvardhan@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Harshvardhan',
            //     'last_name' => 'Singh',
            //     'phone' => '+919999999913',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Sudhanshu Awasthi',
            //     'email' => 'sudhanshu.awasthi@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Sudhanshu',
            //     'last_name' => 'Awasthi',
            //     'phone' => '+919999999941',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Shivam Dave',
            //     'email' => 'Shivam@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Shivam',
            //     'last_name' => 'Dave',
            //     'phone' => '+919999999935',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Samiksha Kaushik',
            //     'email' => 'samiksha@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Samiksha',
            //     'last_name' => 'Kaushik',
            //     'phone' => '+919999999932',
            //     'team_id' => '3',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Sakeena',
            //     'email' => 'sakeena@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Sakeena',
            //     'last_name' => '',
            //     'phone' => '+919999999930',
            //     'team_id' => '3',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Ravikant',
            //     'email' => 'Ravikant@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Ravikant',
            //     'last_name' => '',
            //     'phone' => '+919999999927',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
            // [
            //     'name' => 'Nikhil Srivastava',
            //     'email' => 'Nikhil.srivastava@digirockett.com',
            //     'password' => 'password',
            //     'first_name' => 'Nikhil',
            //     'last_name' => 'Srivastava',
            //     'phone' => '+919999999922',
            //     'team_id' => '4',
            //     'reporting_manager_id' => '',
            // ],
 
        ];

        foreach ($users as $userData) {
            // Create the user
            $user = User::create([
                'name' => $userData['name'],
                'email' => $userData['email'],
                'password' => Hash::make($userData['password']),
                'email_verified_at' => now(),
                'is_active' => 1,
            ]);

            // Create the corresponding employee record
            // Note: reporting_manager_id will be set by ReportingManagerSeeder
            Employee::create([
                'user_id' => $user->id,
                'first_name' => $userData['first_name'],
                'last_name' => $userData['last_name'],
                'phone' => $userData['phone'],
                'team_id' => $userData['team_id'],
            ]);
        }
    }
}
